# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efd50f1ec88330a236b8b5214acb60f6387d16cbfe198731781d8febc47270a66d0b5c55f0189b585996a1e0e20f53187a947c862761b6e2221ee99683b5e611

test:
  secret_key_base: efd50f1ec88330a236b8b5214acb60f6387d16cbfe198731781d8febc47270a66d0b5c55f0189b585996a1e0e20f53187a947c862761b6e2221ee99683b5e611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
